CREATE TABLE IF NOT EXISTS `weekly_plan_generation_jobs` (
  `id` int AUTO_INCREMENT NOT NULL,
  `requestId` varchar(36) NOT NULL,
  `organizationId` int NOT NULL,
  `teacherId` int NOT NULL,
  `classId` int,
  `ageGroup` enum('nursery','kg1','kg2','kg3') NOT NULL,
  `weekStartDate` varchar(10) NOT NULL,
  `weekEndDate` varchar(10) NOT NULL,
  `theme` varchar(300) NOT NULL,
  `language` enum('ar','en','bilingual') NOT NULL DEFAULT 'ar',
  `status` enum('pending','processing','completed','failed') NOT NULL DEFAULT 'pending',
  `stage` enum('queued','generating','validating','saving','completed','failed') NOT NULL DEFAULT 'queued',
  `progress` int NOT NULL DEFAULT 5,
  `planId` int,
  `errorCode` varchar(50),
  `errorMessage` text,
  `attempts` int NOT NULL DEFAULT 0,
  `startedAt` timestamp NULL,
  `completedAt` timestamp NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `weekly_plan_generation_jobs_id` PRIMARY KEY(`id`),
  CONSTRAINT `weekly_plan_generation_jobs_requestId_unique` UNIQUE(`requestId`),
  INDEX `idx_weekly_plan_jobs_org_user_created` (`organizationId`, `teacherId`, `createdAt`),
  INDEX `idx_weekly_plan_jobs_status_updated` (`status`, `updatedAt`)
);
