import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Separator } from "@/components/ui/separator";
import { toast } from "sonner";
import {
  FileText,
  Download,
  Printer,
  Languages,
  Brain,
  Sparkles,
  Loader2,
} from "lucide-react";
import { useTranslation } from "react-i18next";

interface Props {
  childId: number;
  childName?: string;
}

export default function DevelopmentReport({ childId, childName }: Props) {
  const { t, i18n } = useTranslation();
  const isAr = i18n.language === "ar";
  const [language, setLanguage] = useState<"ar" | "en">("ar");
  const [reportType, setReportType] = useState<"professional" | "parent">("parent");
  const [report, setReport] = useState<any>(null);
  const [generating, setGenerating] = useState(false);

  const generateReport = trpc.development.generateReport.useMutation({
    onSuccess: (data) => {
      setReport(data);
      setGenerating(false);
      toast.success(language === "ar" ? isAr ? "تم إنشاء التقرير بنجاح" : "Report created successfully" : "Report generated successfully");
    },
    onError: (err) => {
      setGenerating(false);
      toast.error(language === "ar" ? isAr ? "فشل في إنشاء التقرير" : "Failed to Create Report" : "Failed to generate report");
    },
  });

  const handleGenerate = () => {
    setGenerating(true);
    generateReport.mutate({ childId, language, type: reportType });
  };

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    // Use browser print to PDF
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      toast.error(isAr ? "يرجى السماح بالنوافذ المنبثقة" : "Please allow pop-ups");
      return;
    }

    const isRTL = language === "ar";
    const fontFamily = isRTL ? "'Noto Sans Arabic', 'Segoe UI', sans-serif" : "'Segoe UI', sans-serif";
    
    printWindow.document.write(`
      <!DOCTYPE html>
      <html dir="${isRTL ? "rtl" : "ltr"}" lang="${language}">
      <head>
        <meta charset="UTF-8">
        <title>${report?.report?.title || "Development Report"}</title>
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Arabic:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body {
            font-family: ${fontFamily};
            line-height: 1.8;
            color: #1a1a1a;
            padding: 40px;
            direction: ${isRTL ? "rtl" : "ltr"};
          }
          .header {
            text-align: center;
            padding-bottom: 24px;
            border-bottom: 3px solid #059669;
            margin-bottom: 32px;
          }
          .header h1 {
            font-size: 24px;
            color: #059669;
            margin-bottom: 8px;
          }
          .header .meta {
            font-size: 14px;
            color: #666;
          }
          .section {
            margin-bottom: 28px;
            page-break-inside: avoid;
          }
          .section h2 {
            font-size: 18px;
            color: #1e3a5f;
            padding-bottom: 8px;
            border-bottom: 2px solid #e5e7eb;
            margin-bottom: 12px;
          }
          .section p {
            font-size: 14px;
            text-align: justify;
            margin-bottom: 8px;
          }
          .footer {
            margin-top: 40px;
            padding-top: 16px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            font-size: 12px;
            color: #999;
          }
          @media print {
            body { padding: 20px; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${report?.report?.title || ""}</h1>
          <div class="meta">
            ${isRTL ? (isAr ? "الطفل" : "Child") : "Child"}: ${childName || report?.child?.name || ""} | 
            ${isRTL ? isAr ? "العمر" : "Age" : "Age"}: ${report?.child?.age || ""} ${isRTL ? isAr ? "شهراً" : "Months" : "months"} | 
            ${isRTL ? (isAr ? "التاريخ" : "Date") : "Date"}: ${new Date().toLocaleDateString(isRTL ? "ar-SA" : "en-US")}
          </div>
        </div>
        ${report?.report?.sections?.map((s: any) => `
          <div class="section">
            <h2>${s.heading}</h2>
            <p>${s.content.replace(/\n/g, "</p><p>")}</p>
          </div>
        `).join("") || ""}
        <div class="footer">
          ${isRTL ? (isAr ? "تقرير صادر من مركز النمو والتطور - Naashah" : "Report from the Growth and Development Center - Naashah") : "Generated by Growth & Development Center - Naashah"}
        </div>
      </body>
      </html>
    `);
    printWindow.document.close();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  };

  return (
    <div className="space-y-6" dir={language === "ar" ? "rtl" : "ltr"}>
      {/* Controls */}
      <Card className="border-0 shadow-sm">
        <CardContent className="p-5">
          <div className="flex items-center gap-4 flex-wrap">
            <div className="flex items-center gap-2">
              <Languages className="w-4 h-4 text-muted-foreground" />
              <Select value={language} onValueChange={(v) => setLanguage(v as "ar" | "en")}>
                <SelectTrigger className="w-32">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="ar">{isAr ? "العربية" : "Arabic"}</SelectItem>
                  <SelectItem value="en">English</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="flex items-center gap-2">
              <FileText className="w-4 h-4 text-muted-foreground" />
              <Select value={reportType} onValueChange={(v) => setReportType(v as "professional" | "parent")}>
                <SelectTrigger className="w-44">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="parent">{language === "ar" ? isAr ? "نسخة ولي الأمر" : "Parent Version" : "Parent Version"}</SelectItem>
                  <SelectItem value="professional">{language === "ar" ? isAr ? "نسخة مهنية تفصيلية" : "Professional Detailed Version" : "Professional Version"}</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button onClick={handleGenerate} disabled={generating} className="bg-emerald-600 hover:bg-emerald-700">
              {generating ? (
                <>
                  <Loader2 className="w-4 h-4 ml-2 animate-spin" />
                  {language === "ar" ? (isAr ? "جاري الإنشاء..." : "Creating...") : "Generating..."}
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 ml-2" />
                  {language === "ar" ? (isAr ? "إنشاء التقرير" : "Create Report") : "Generate Report"}
                </>
              )}
            </Button>
            {report && (
              <>
                <Button variant="outline" onClick={handleDownloadPDF}>
                  <Download className="w-4 h-4 ml-2" />
                  {language === "ar" ? (isAr ? "تحميل PDF" : "Download PDF") : "Download PDF"}
                </Button>
                <Button variant="outline" onClick={handlePrint}>
                  <Printer className="w-4 h-4 ml-2" />
                  {language === "ar" ? (isAr ? "طباعة" : "Print") : "Print"}
                </Button>
              </>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Report Preview */}
      {generating && (
        <Card className="border-0 shadow-sm">
          <CardContent className="py-12 text-center">
            <div className="w-16 h-16 rounded-full bg-emerald-100 flex items-center justify-center mx-auto mb-4">
              <Brain className="w-8 h-8 text-emerald-600 animate-pulse" />
            </div>
            <p className="font-medium text-foreground">
              {language === "ar" ? isAr ? "يتم تحليل بيانات الطفل وإنشاء التقرير..." : "Child data is analyzed and report generated..." : "Analyzing child data and generating report..."}
            </p>
            <p className="text-sm text-muted-foreground mt-2">
              {language === "ar" ? isAr ? "قد يستغرق هذا بضع ثوانٍ" : "This may take a few seconds" : "This may take a few seconds"}
            </p>
          </CardContent>
        </Card>
      )}

      {report && !generating && (
        <Card className="border-0 shadow-md print:shadow-none" id="report-content">
          <CardHeader className="bg-gradient-to-br from-emerald-50 to-teal-50 dark:from-emerald-950/20 dark:to-teal-950/10 rounded-t-lg border-b">
            <div className="text-center">
              <CardTitle className="text-xl text-emerald-700 dark:text-emerald-400">
                {report.report?.title}
              </CardTitle>
              <p className="text-sm text-muted-foreground mt-2">
                {language === "ar" ? (isAr ? "الطفل" : "Child") : "Child"}: {childName || report.child?.name} | {" "}
                {language === "ar" ? isAr ? "العمر" : "Age" : "Age"}: {report.child?.age} {language === "ar" ? isAr ? "شهراً" : "Months" : "months"} | {" "}
                {language === "ar" ? (isAr ? "التاريخ" : "Date") : "Date"}: {new Date().toLocaleDateString(language === "ar" ? "ar-SA" : "en-US")}
              </p>
            </div>
          </CardHeader>
          <CardContent className="p-6 space-y-6">
            {/* Summary */}
            {report.report?.summary && (
              <div className="bg-muted/30 rounded-lg p-4 border-r-4 border-emerald-500">
                <p className="text-sm leading-relaxed">{report.report.summary}</p>
              </div>
            )}

            {/* Sections */}
            {report.report?.sections?.map((section: any, idx: number) => (
              <div key={idx} className="space-y-2">
                <h3 className="text-base font-bold text-foreground flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-emerald-500" />
                  {section.heading}
                </h3>
                <Separator />
                <div className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">
                  {section.content}
                </div>
              </div>
            ))}

            {/* Footer */}
            <div className="pt-4 border-t text-center text-xs text-muted-foreground">
              {language === "ar" 
                ? (isAr ? "تقرير صادر من مركز النمو والتطور - Naashah" : "Report from the Growth and Development Center - Naashah") 
                : "Generated by Growth & Development Center - Naashah"}
            </div>
          </CardContent>
        </Card>
      )}

      {!report && !generating && (
        <Card className="border-0 shadow-sm">
          <CardContent className="py-12 text-center text-muted-foreground">
            <FileText className="w-12 h-12 mx-auto mb-3 opacity-30" />
            <p className="font-medium">
              {language === "ar" ? isAr ? "لم يتم إنشاء تقرير بعد" : "No report has been generated yet" : "No report generated yet"}
            </p>
            <p className="text-sm mt-1">
              {language === "ar" 
                ? isAr ? "اختر اللغة ونوع التقرير ثم اضغط على إنشاء التقرير" : "Select language and report type, then click Generate Report" 
                : "Select language and report type, then click Generate Report"}
            </p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
